### ISSUE TITLE
Bug with function bipartite_D3

### ISSUE THREAD

**Issue by iremendoza** [cran/bipartiteD3#1]
I am trying to reproduce the example and there is a bug with the bipartite_D3 function. I have a RStudio Version 1.4.1103 and a Java  8 updated on July 2021.

I have seen that the last update of the package is old, from 2019. Indeed, I used this function with the same computer than now in 2020 and it worked out, so I guess that there must be an issue with the new Java version.

I appreciate any recommendation or correction of the bug.
Best,
Irene

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by iremendoza** [comment]
Apologies for the mistake and thanks for the feedback. I have written an issue in the repository of the maintainer.
